# Generated by Django 4.1 on 2024-04-01 11:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("books_service", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="book",
            options={"ordering": ["-title"]},
        ),
    ]
