# Generated by Django 4.1 on 2024-04-02 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payment_system", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="payment",
            name="session_id",
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name="payment",
            name="session_url",
            field=models.URLField(blank=True, null=True),
        ),
    ]
