# Generated by Django 4.1 on 2024-04-01 15:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("books_service", "0002_alter_book_options"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("borrowings", "0002_borrowing_is_active"),
    ]

    operations = [
        migrations.AddField(
            model_name="borrowing",
            name="book",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="books_service.book",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="borrowing",
            name="user",
            field=models.ForeignKey(
                default=0,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=False,
        ),
    ]
